### ISSUE TITLE
When I train to epoch 10, I will encounter an error message

### ISSUE THREAD

**Issue by shlsp** [goutamyg/SMAT#8]
When I train to epoch 10, I will encounter an error message, which is “RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[1, 128, 32, 32] to have 3 channels, but got 128 channels instead”. Can you help me solve this problem? Thank you.

**Comment by goutamyg** [comment]
Hi, thank you for your interest in our work. 

Please comment [these lines](https://github.com/goutamyg/SMAT/blob/main/lib/test/tracker/mobilevitv2_track.py#L72-L82) and replace with ```self.z_dict1 = template.tensors```

Let me know if this fixes your error.

**Comment by shlsp** [comment]
> Hi, thank you for your interest in our work.
> 
> Please comment [these lines](https://github.com/goutamyg/SMAT/blob/main/lib/test/tracker/mobilevitv2_track.py#L72-L82) and replace with `self.z_dict1 = template.tensors`
> 
> Let me know if this fixes your error.

The problem has been resolved. Thank you very much for the author's answer.

**Comment by kapilsingla22** [comment]
Hii @goutamyg 
While training, On the first epoch only, I am also getting the same type of error and after commenting the lines told by you, i am still getting the same error, can you help me with it. Thank you
RuntimeError: Given groups=1, weight of size [256, 128, 1, 1], expected input[128, 3, 128, 128] to have 128 channels, but got 3 channels instead
